/* ============================================================
   PROJECT DATA
   ============================================================ */

window.PROJECTS = [
  {
    slug: "ustawienia-domyslne",
    no: "01",
    title: { pl: "Ustawienia domyślne", en: "Default Settings" },
    year: "2024",
    category: { pl: "Dokument", en: "Documentary" },
    place: { pl: "O sztucznej inteligencji", en: "On artificial intelligence" },
    works: 17,
    thumb: "images/ustawienia/03.webp",
    caption: {
      pl: "Glicze, artefakty i błędy obrazów generowanych przez sztuczną inteligencję. Pytanie o prawdę fotograficzną w epoce AI. Mokra płyta kolodionowa.",
      en: "Glitches, artifacts and errors of AI-generated images. A question about photographic truth in the age of AI. Wet plate collodion."
    },
    description: {
      pl: "Ustawienia domyślne to predefiniowane wartości lub konfiguracje, które są automatycznie przypisywane do różnych opcji w oprogramowaniu, urządzeniach elektronicznych czy systemach operacyjnych, jeśli użytkownik nie dokonał żadnych zmian.\n\nPodczas generowania obrazów przy użyciu sztucznej inteligencji mogą pojawić się różne artefakty, glicze i błędy. Typowe problemy: artefakty w wysokiej częstotliwości, rozmyte obrazy, przesunięcia i zniekształcenia geometryczne, powtarzające się wzorce, przypadkowe elementy.\n\nUstawienia domyślne poruszają także pytanie, które istnieje od wynalezienia fotografii w 1826 roku: czy fotografia ukazuje prawdę? Obrazy generowane przez sztuczną inteligencję opierają się na zaczerpniętych z internetu zdjęciach, które często zostały poddane silnej postprodukcji, modyfikacji i ingerencji cyfrowej. Model uczy się na przetworzonych danych i „nieprawdziwych\" wizjach, przez co tworzy własną interpretację rzeczywistości.\n\nTechnika: zdjęcia wykonane na czarno-białym negatywie średnioformatowym i pod powiększalnikiem przeniesione na mokrą płytę kolodionową.",
      en: "Default settings are predefined values or configurations automatically assigned to various options in software, electronic devices, or operating systems when the user has not made any changes.\n\nWhen generating images with artificial intelligence, various artifacts, glitches, and errors may appear. Typical issues include: high-frequency artifacts, blurred images, geometric distortions and shifts, repeating patterns, random elements.\n\nDefault settings also raise the question that has existed since photography was invented in 1826: does photography show the truth? Images generated by artificial intelligence are based on photographs sourced from the internet, often heavily post-processed, modified, and digitally altered. The model learns from processed data and \"untrue\" visions, creating its own interpretation of reality.\n\nTechnique: photographs taken on a black-and-white medium-format negative and transferred under the enlarger onto wet collodion plate."
    },
    images: Array.from({length: 17}, (_, i) =>
      `images/ustawienia/${String(i+1).padStart(2,"0")}.webp`)
  },
  {
    slug: "superpozycja",
    no: "02",
    title: { pl: "Superpozycja", en: "Superposition" },
    year: "2023",
    category: { pl: "Kreacja / Portret", en: "Constructed / Portrait" },
    place: { pl: "Kwantowa wizja", en: "Quantum vision" },
    works: 8,
    caption: {
      pl: "Fotograficzny zapis kwantowej superpozycji — jednoczesność przeszłości, teraźniejszości i przyszłości. To, co widzimy, zależy od perspektywy obserwatora.",
      en: "A photographic record of quantum superposition — the simultaneity of past, present, and future. What we see depends on the observer's perspective."
    },
    description: {
      pl: "Superpozycja to fundamentalna zasada fizyki kwantowej, oznaczająca, że cząstki lub obiekty mogą jednocześnie istnieć w wielu wzajemnie wykluczających się stanach. Innymi słowy, mogą znajdować się w dwóch lub więcej miejscach jednocześnie, dopóki nie zostaną zmierzone.\n\nZdjęcia z tego projektu są próbą fotograficznego zapisu, jak wyglądałby świat, gdyby zjawisko superpozycji było dostrzegalne przez przeciętnego obserwatora. Cykl metaforycznie ukazuje jednoczesność przeszłości, teraźniejszości i przyszłości, wskazując, że drobne zmiany mogą wpłynąć na nasz punkt widzenia. To, co widzimy, zależy zawsze od perspektywy obserwatora.",
      en: "Superposition is a fundamental principle of quantum physics, meaning that particles or objects can simultaneously exist in several mutually exclusive states. In other words, they can be in two or more places at once, until they are measured.\n\nThe photographs in this project attempt to record what the world would look like if superposition were perceptible to the average observer. The series metaphorically reveals the simultaneity of past, present, and future, showing how small changes can shift our point of view. What we see always depends on the observer's perspective."
    },
    images: Array.from({length: 8}, (_, i) =>
      `images/superpozycja/${String(i+1).padStart(2,"0")}.webp`)
  },
  {
    slug: "gra-o-tron",
    no: "03",
    title: { pl: "Gra o tron", en: "Game of Thrones" },
    year: "2022",
    category: { pl: "Dokument / Found", en: "Documentary / Found" },
    place: { pl: "Walka polityczna", en: "Political fight" },
    works: 12,
    flashEffect: true,
    caption: {
      pl: "Polityczna ikonografia polskiej prowincji. Plakaty, ołtarzyki, prowizoryczne pomniki — krajobraz przed wyborami.",
      en: "Political iconography of the Polish countryside. Posters, makeshift shrines, monuments — the landscape before an election."
    },
    images: Array.from({length: 12}, (_, i) =>
      `images/gra_o_tron/${String(i+1).padStart(2,"0")}.webp`)
  },
  {
    slug: "nowa-topografia",
    no: "04",
    title: { pl: "Nowa topografia Polski", en: "New Topography of Poland" },
    year: "2022",
    category: { pl: "Dokument / Krajobraz", en: "Documentary / Landscape" },
    place: { pl: "Polska moim okiem", en: "Poland through my eye" },
    works: 14,
    caption: {
      pl: "Polska moim okiem — krajobraz peryferii, ogrodzeń, tablic, prowizorek. Ślady ingerencji człowieka w minimalistyczny krajobraz.",
      en: "Poland through my eye — a landscape of edges, fences, notice boards, makeshift things. Traces of human intervention in a minimalist landscape."
    },
    images: Array.from({length: 14}, (_, i) =>
      `images/topografia/${String(i+1).padStart(2,"0")}.webp`)
  },
  {
    slug: "labirynt",
    no: "05",
    title: { pl: "Labirynt", en: "Labyrinth" },
    year: "2024",
    category: { pl: "Dokument / Książka", en: "Documentary / Book" },
    place: { pl: "Zagubieni", en: "The Lost" },
    works: 15,
    flashEffect: true,
    caption: {
      pl: "Ludzie uwikłani w pułapki małych miasteczek. Cykl o błądzeniu, zawieszeniu i braku perspektyw. ITF Opawa.",
      en: "People caught in the traps of small towns. A series on drift, suspension, and dead ends. ITF Opava."
    },
    description: {
      pl: "Labirynt od wieków budzi w nas skojarzenia z czymś więcej niż tylko zbiorem korytarzy i zagadek — stał się symbolem życia, w którym łatwo zatracić się w niekończącej się sieci wyborów i pułapek. Dawne mity, jak ten o kreteńskim Labiryncie i Minotaurze, pokazują, jak złożone struktury mogą nie tylko inspirować, ale i przytłaczać. Dziś obraz labiryntu znajduje swoje miejsce w sztuce, literaturze, psychologii czy grach komputerowych, gdzie symbolizuje zarówno proces odkrywania, jak i zagubienie w obliczu życiowych wyzwań.\n\nCykl opowiada o ludziach uwikłanych przez małe miasteczka.\n\ndroga bez wyjścia / pułapka\n\n/ przytłoczenie / alkoholizm / brak perspektyw / reset\n\nbłądzenie / zawieszenie\n\n/ poszukiwanie / konserwatyzm / rodzina\n\ntotalna chujnia / uzależnienie / stagnacja / beznadzieja\n\nbunt / bieda / ocena / irytacja / depresja",
      en: "For centuries the labyrinth has evoked more than just a set of corridors and riddles — it has become a symbol of life, in which it is easy to lose oneself in an endless network of choices and traps. Ancient myths, such as that of the Cretan Labyrinth and the Minotaur, show how complex structures can both inspire and overwhelm. Today the image of the labyrinth finds its place in art, literature, psychology, and computer games, where it symbolizes both the process of discovery and disorientation in the face of life's challenges.\n\nThe series tells of people entangled by small towns.\n\ndead end / trap\n\n/ overwhelm / alcoholism / no prospects / reset\n\ndrift / suspension\n\n/ searching / conservatism / family\n\ntotal mess / addiction / stagnation / hopelessness\n\nrebellion / poverty / judgment / irritation / depression"
    },
    images: Array.from({length: 15}, (_, i) =>
      `images/labirynt/${String(i+1).padStart(2,"0")}.webp`)
  },
  {
    slug: "nocne-ptaki",
    no: "06",
    title: { pl: "Nocne Ptaki Późno Wracają Do Domu", en: "Night Birds Come Home Late" },
    year: "2025",
    category: { pl: "Dokument / Reportaż / Street", en: "Documentary / Reportage / Street" },
    place: { pl: "Nocny styl życia", en: "Nocturnal life" },
    works: 8,
    flashEffect: true,
    caption: {
      pl: "Zapis dokumentalny nocnego stylu życia. Refleksja nad normami społecznymi.",
      en: "A documentary record of nocturnal life. A reflection on social norms."
    },
    // description: pełny opis do uzupełnienia później
    images: [
      "images/nocne-ptaki/04.webp",
      "images/nocne-ptaki/03.webp",
      "images/nocne-ptaki/01.webp",
      "images/nocne-ptaki/07.webp",
      "images/nocne-ptaki/06.webp",
      "images/nocne-ptaki/08.webp",
      "images/nocne-ptaki/02.webp",
      "images/nocne-ptaki/05.webp"
    ]
  },
  {
    slug: "danie-dnia",
    no: "07",
    title: { pl: "Danie dnia", en: "Dish of the Day" },
    year: "2025",
    category: { pl: "Studium / Dokument / Ekologia", en: "Studio / Documentary / Ecology" },
    place: { pl: "Marnowanie żywności", en: "Food waste" },
    works: 20,
    book: true,
    thumb: "images/danie-dnia/book/19.webp",
    caption: {
      pl: "Warzywa i owoce przeznaczone przez sklep do wyrzucenia — sfotografowane, potem zjedzone. Projekt dokumentalny o marnowaniu żywności.",
      en: "Vegetables and fruit marked for disposal by the shop — photographed, then eaten. A documentary project on food waste."
    },
    description: {
      pl: "W Polsce rocznie marnuje się ok. 5 mln ton żywności. Aż 60% tej skali pochodzi z gospodarstw domowych — to ok. 3 mln ton wyrzucanego jedzenia rocznie. 45% Polaków przyznaje się do wyrzucania żywności przynajmniej od czasu do czasu. Najczęściej do kosza trafiają wędliny (36%), warzywa (34%) i owoce (30%).",
      en: "In Poland, around 5 million tonnes of food are wasted every year. As much as 60% of this comes from households — about 3 million tonnes of discarded food per year. 45% of Poles admit to throwing food away at least occasionally. The most commonly discarded products are cold cuts (36%), vegetables (34%), and fruit (30%)."
    },
    images: Array.from({length: 20}, (_, i) =>
      `images/danie-dnia/book/${String(i+1).padStart(2,"0")}.webp`)
  }
];

/* ============================================================
   DANIE DNIA — dane książki (flipbook)
   Odwzorowanie układu stron z PDF-a: okładka, strona tytułowa,
   stopka redakcyjna, sekcje/przepisy + zdjęcia warzyw, zakończenie,
   tylna okładka. Treść przepisów w oryginale (PL) — to reprodukcja
   realnej książki kucharskiej.
   ============================================================ */
window.DANIE_BOOK = (function () {
  const P = n => `images/danie-dnia/book/${String(n).padStart(2, "0")}.webp`;

  const recipes = [
    {
      section: { pl: "Napój", en: "Drink" },
      title: "Lemoniada",
      ing: [
        "4 cytryny",
        "1 szklanka ksylitolu",
        "6–8 szklanek wody mineralnej, źródlanej lub filtrowanej",
        "1 gruszka",
        "1 granat",
        "1 marakuja",
        "lód do podania"
      ],
      steps: "Wyciśnij sok z cytryn, używając wyciskarki do cytrusów lub ręcznie przez sitko tak, aby oddzielić nasiona. W rondelku zagotuj 1 szklankę wody i dodaj ksylitol. Gotuj na małym ogniu, mieszając, aż ksylitol się rozpuści. Następnie zdejmij z ognia i ostudź. W dużym dzbanku połącz sok z cytryn z przestudzonym syropem z ksylitolu. Dodaj resztę wody (około 5–7 szklanek) do dzbanka i dokładnie wymieszaj. Dodaj pestki granatu i marakui oraz plasterki gruszki, aby wzbogacić smak i kolor lemoniady. Odstaw lemoniadę na kilka minut, aby składniki się przegryzły i napój nabrał pełni smaku."
    },
    {
      section: { pl: "Przystawka", en: "Starter" },
      title: "Twarożek z Rzodkiewką",
      ing: [
        "300 g twarogu w kostce, np. półtłusty",
        "1 mały pęczek rzodkiewki",
        "1 czubata łyżka śmietany",
        "2 ząbki czosnku",
        "1/4 łyżeczki soli",
        "większa szczypta pieprzu czarnego",
        "1 łyżeczka szczypiorku"
      ],
      steps: "Rzodkiewki umyj i pokrój w drobną kostkę, czosnek przeciśnij przez praskę. Przełóż twaróg do miski i rozgnieć go widelcem, do uzyskania jednolitej konsystencji. Do twarogu dodaj śmietanę, drobno posiekane rzodkiewki i czosnek, dopraw solą i pieprzem. Całość dokładnie wymieszaj łyżką. Drobno posiekanym szczypiorkiem udekoruj wierzch twarożku lub dodaj go do środka i wymieszaj. Twarożek podawaj z pokrojoną bagietką lub domowym pieczywem."
    },
    {
      section: { pl: "Zupa", en: "Soup" },
      title: "Polewka Letnia",
      ing: [
        "2 duże kartofle",
        "1 sałata",
        "1 cebula",
        "1 pietruszka",
        "1 łyżka masła",
        "sól",
        "pieprz"
      ],
      steps: "Obrane ziemniaki umyj i pokrój w plasterki, następnie zalej je gorącą wodą i gotuj przez około 10 minut. Po tym czasie ziemniaki odcedź. Pokrojoną drobno i obraną pietruszkę, cebulę, sałatę i podgotowane ziemniaki włóż do rondelka, zalej ½ litra wody i gotuj do miękkości. Następnie przetrzyj ziemniaki przez sito, dodaj łyżkę masła oraz sól i pieprz do smaku."
    },
    {
      section: { pl: "Drugie Danie", en: "Main Course" },
      title: "Lasagne z kapusty",
      ing: [
        "1 kapusta",
        "2 cebule",
        "1 łyżka oleju",
        "3 ząbki czosnku",
        "2 marchewki",
        "3 pieczarki",
        "1 i 1/2 szklanki przecieru pomidorowego",
        "1 łyżka sosu sojowego",
        "1 łyżka płatków drożdżowych",
        "szczypta mielonej kozieradki",
        "pieprz",
        "sól",
        "suszona bazylia"
      ],
      steps: "Kapustę obgotuj i zdejmij z niej zewnętrzne liście, wycinając z nich zgrubiałe części. Naczynie żaroodporne (15 × 25 centymetrów) wyłóż warstwą ugotowanych liści kapusty. Cebule obierz i pokrój w drobną kostkę. Na patelni rozgrzej olej, dodaj cebulę oraz przeciśnięty przez praskę ząbek czosnku. Obierz marchewki, zetrzyj je na tarce o grubych oczkach i podsmaż razem z cebulą. Następnie dodaj pokrojone w kostkę pieczarki. Farsz dopraw kozieradką, bazylią, solą oraz pieprzem. Dodaj 1 szklankę przecieru pomidorowego i podsmaż do odparowania wody. Na koniec dopraw sosem sojowym, a w razie potrzeby pieprzem i solą. Farsz wyłóż na liście kapusty, a następnie przykryj go kolejną warstwą liści. Wierzch zalej ½ szklanki przecieru pomidorowego wymieszanego z płatkami drożdżowymi, solą i pieprzem. Piecz całość przez 20 minut w temperaturze 180 stopni."
    },
    {
      section: { pl: "Deser", en: "Dessert" },
      title: "Szarlotka z Mandarynkami",
      ing: [
        "Ciasto:",
        "5 żółtek",
        "250 g masła",
        "5 łyżek cukru",
        "1/2 kg mąki tortowej",
        "3 łyżeczki proszku do pieczenia",
        "sok z połowy cytryny",
        "3 łyżki tartej bułki",
        "Beza:",
        "5 białek",
        "szczypta soli",
        "1 szklanka cukru",
        "Dodatkowo:",
        "1,5 kg jabłek i mandarynek (proporcje 1:1)",
        "3 łyżki cukru trzcinowego",
        "cynamon"
      ],
      steps: "Utrzyj w misie żółtka z cukrem i masłem. Przesiej do misy mąkę z proszkiem do pieczenia, dodaj sok z cytryny i zmiksuj całość, aż powstanie konsystencja przypominająca „żwirek”. Odsyp 1/3 ciasta na kruszonkę, a resztę zagnieć. Większą część ciasta przełóż na blaszkę (30 × 40 cm) wyłożoną papierem do pieczenia i dociśnij, wyrównując powierzchnię. Jabłka obierz, pokrój w plasterki i ułóż na cieście posypanym tartą bułką. Na jabłkach ułóż odsączone mandarynki. Posyp owoce cukrem i cynamonem. Białka ubij ze szczyptą soli, a następnie stopniowo dodawaj cukier, kontynuując ubijanie. Wyłóż powstałą masę na jabłka, a na wierzchu rozsyp pozostałą część ciasta. Piecz przez 40 minut w temperaturze 180°C (góra–dół), następnie przełącz piekarnik tylko na dolne grzanie i piecz jeszcze przez 15 minut. Jeśli góra ciasta za bardzo się rumieni, przykryj ją papierem do pieczenia. Po ostygnięciu posyp ciasto cukrem pudrem."
    }
  ];

  // Liczba zdjęć przypadająca na każdą sekcję (kolejność = recipes)
  const photoGroups = [4, 3, 4, 6, 3]; // razem 20

  // Budowa płaskiej listy stron — odwzorowanie rozkładówek z PDF.
  // Para (left,right) tworzy rozkładówkę: indeksy (1,2)(3,4)... ; okładka sama.
  const pages = [];
  pages.push({ type: "cover" });
  pages.push({ type: "title" });
  pages.push({ type: "colophon" });

  let ph = 0;
  recipes.forEach((r, ri) => {
    // zdjęcia tej grupy (przed sekcją w sekwencji PDF — patrz mapowanie)
    for (let k = 0; k < photoGroups[ri]; k++) {
      pages.push({ type: "blank" });
      pages.push({ type: "photo", src: P(++ph) });
    }
    // strona przepisu (lewa) + pusta (prawa)
    pages.push({ type: "recipe", r });
    pages.push({ type: "blank" });
  });

  pages.push({ type: "blank" });
  pages.push({ type: "closing" });
  pages.push({ type: "backcover" });

  return { pages, recipes };
})();

/* ============================================================
   ACHIEVEMENTS / AKTUALNOŚCI — wystawy, pokazy, publikacje, etc.
   Każdy wpis musi mieć `dateISO` (YYYY-MM-DD) — używane do
   automatycznego sortowania chronologicznie (najnowsze u góry)
   oraz do Schema.org / SEO.
   ============================================================ */
window.ACHIEVEMENTS = [
  {
    id: "itf-opava-start-2025",
    dateISO: "2025-06-16",
    date: {
      pl: "16 czerwca 2025",
      en: "16 June 2025"
    },
    type: { pl: "Edukacja", en: "Education" },
    title: {
      pl: "Rozpoczęcie studiów — ITF Opawa",
      en: "Studies started — ITF Opava"
    },
    place: {
      pl: "Institut tvůrčí fotografie, Uniwersytet Śląski w Opawie, Czechy",
      en: "Institut tvůrčí fotografie, Silesian University in Opava, Czech Republic"
    },
    description: {
      pl: "Rozpoczęcie studiów w Instytucie Fotografii Twórczej (Institut tvůrčí fotografie) na Uniwersytecie Śląskim w Opawie — jednej z najbardziej prestiżowych europejskich szkół fotografii artystycznej. Założony w 1990 roku, kształci kolejne pokolenia fotografów z całego regionu Europy Środkowej.",
      en: "Beginning studies at the Institute of Creative Photography (Institut tvůrčí fotografie) at Silesian University in Opava — one of Europe's most prestigious schools of art photography. Founded in 1990, it has shaped generations of photographers across Central Europe."
    },
    links: [
      {
        label: { pl: "Strona ITF Opawa", en: "ITF Opava website" },
        url: "https://itf.fpf.slu.cz/"
      }
    ],
    images: [
      "images/achievements/itf-opava-start-2025/01.webp",
      "images/achievements/itf-opava-start-2025/02.webp",
      "images/achievements/itf-opava-start-2025/03.webp",
      "images/achievements/itf-opava-start-2025/04.webp"
    ]
  },
  {
    id: "fotoartfestival-dias-show-2025",
    dateISO: "2025-10-11",
    date: {
      pl: "10 – 12 października 2025",
      en: "10 – 12 October 2025"
    },
    type: { pl: "Laureat / Pokaz festiwalowy", en: "Laureate / Festival screening" },
    title: {
      pl: "DIAS SHOW — laureat XI FotoArtFestival",
      en: "DIAS SHOW — XI FotoArtFestival laureate"
    },
    place: {
      pl: "Foto Art Festival, Bielsko-Biała",
      en: "Foto Art Festival, Bielsko-Biała"
    },
    description: {
      pl: "Wyróżnienie w międzynarodowym konkursie multimedialnym DIAS SHOW podczas 11. edycji Foto Art Festival w Bielsku-Białej. Cykl „Labirynt” znalazł się wśród dziewięciu zwycięskich prac. Laureaci otrzymują możliwość zorganizowania wystawy indywidualnej w Galerii Fotografii B&B lub podczas kolejnej edycji festiwalu. DIAS SHOW łączy fotografię z muzyką i narracją, prezentując dynamiczne sekwencje obrazów na dużym ekranie.",
      en: "Distinction in the international multimedia competition DIAS SHOW during the 11th edition of Foto Art Festival in Bielsko-Biała. The \"Labirynt\" series was among nine winning works. Laureates receive the opportunity to organise a solo exhibition at the B&B Photography Gallery or during a future festival edition. DIAS SHOW combines photography with music and narration, presenting dynamic image sequences on a large screen."
    },
    links: [
      {
        label: { pl: "Lista laureatów DIAS SHOW", en: "DIAS SHOW laureates" },
        url: "https://fotoartfestival.com/finalisci-dias-show-2025/"
      },
      {
        label: { pl: "Slideshow „Labirynt” na YouTube", en: "\"Labirynt\" slideshow on YouTube" },
        url: "https://www.youtube.com/watch?v=4JCT6mdi9NA"
      }
    ],
    images: [
      "images/achievements/fotoartfestival-dias-show-2025/01.webp",
      "images/achievements/fotoartfestival-dias-show-2025/02.webp",
      "images/achievements/fotoartfestival-dias-show-2025/03.webp"
    ]
  },
  {
    id: "zpaf-przyjecie-2025",
    dateISO: "2025-12-05",
    date: {
      pl: "5 grudnia 2025",
      en: "5 December 2025"
    },
    type: { pl: "Członkostwo", en: "Membership" },
    title: {
      pl: "Przyjęcie do ZPAF — Okręg Warszawski",
      en: "Admission to ZPAF — Warsaw Branch"
    },
    place: {
      pl: "Związek Polskich Artystów Fotografików, Warszawa",
      en: "Union of Polish Art Photographers, Warsaw"
    },
    description: {
      pl: "Przyjęcie do Związku Polskich Artystów Fotografików (ZPAF) — najstarszego i najważniejszego stowarzyszenia fotografów artystycznych w Polsce, działającego od 1947 roku. Rada Artystyczna ZPAF przyjęła w grudniu 2025 grono ośmiorga nowych członków, w tym sześcioro do Okręgu Warszawskiego.",
      en: "Admission to the Union of Polish Art Photographers (ZPAF) — the oldest and most prestigious association of art photographers in Poland, founded in 1947. In December 2025 the ZPAF Artistic Council admitted a group of eight new members, including six to the Warsaw Branch."
    },
    links: [
      {
        label: { pl: "Komunikat ZPAF", en: "ZPAF announcement" },
        url: "https://zpaf.pl/aktualnosci/8-nowych-zpaf-12-2025/"
      }
    ],
    images: [
      "images/achievements/zpaf-przyjecie-2025/06.webp",
      "images/achievements/zpaf-przyjecie-2025/01.webp",
      "images/achievements/zpaf-przyjecie-2025/02.webp",
      "images/achievements/zpaf-przyjecie-2025/03.webp",
      "images/achievements/zpaf-przyjecie-2025/04.webp",
      "images/achievements/zpaf-przyjecie-2025/05.webp"
    ]
  },
  {
    id: "pamietnik-przetrwania-2025",
    dateISO: "2025-12-03",
    date: {
      pl: "3 grudnia 2025 – 10 stycznia 2026",
      en: "3 December 2025 – 10 January 2026"
    },
    type: { pl: "Wystawa indywidualna", en: "Solo exhibition" },
    title: { pl: "Pamiętnik przetrwania", en: "Diary of Survival" },
    place: {
      pl: "Galeria MAL — Terminal Kultury Gocław, Warszawa",
      en: "MAL Gallery — Terminal Kultury Gocław, Warsaw"
    },
    address: {
      pl: "ul. Jana Nowaka-Jeziorańskiego 24, Praga-Południe",
      en: "ul. Jana Nowaka-Jeziorańskiego 24, Praga-Południe"
    },
    description: {
      pl: "Osobisty zapis fotograficzny walki z depresją. Projekt powstał z potrzeby przełamania społecznego tabu wokół chorób psychicznych i dotarcia do osób zmagających się z podobnymi doświadczeniami — z myślą, że prośba o pomoc nie jest oznaką słabości, lecz odwagą.",
      en: "A personal photographic record of struggle with depression. The project was born from the need to break the social taboo around mental illness and to reach others fighting similar battles — with the conviction that asking for help is not a sign of weakness, but of courage."
    },
    images: [
      "images/achievements/pamietnik-przetrwania-2025/01.webp",
      "images/achievements/pamietnik-przetrwania-2025/02.webp",
      "images/achievements/pamietnik-przetrwania-2025/03.webp",
      "images/achievements/pamietnik-przetrwania-2025/04.webp",
      "images/achievements/pamietnik-przetrwania-2025/05.webp",
      "images/achievements/pamietnik-przetrwania-2025/06.webp"
    ]
  },
  {
    id: "w-glowie-sie-nie-miesci-2025",
    dateISO: "2025-09-05",
    date: {
      pl: "5 – 19 września 2025",
      en: "5 – 19 September 2025"
    },
    type: { pl: "Wystawa indywidualna", en: "Solo exhibition" },
    title: { pl: "W głowie się nie mieści", en: "W głowie się nie mieści" },
    place: {
      pl: "Lokal Bródno, Warszawa",
      en: "Lokal Bródno, Warsaw"
    },
    address: {
      pl: "ul. Kondratowicza 18b/406",
      en: "ul. Kondratowicza 18b/406"
    },
    description: {
      pl: "Indywidualna wystawa łącząca cztery cykle artysty — „Pamiętnik przetrwania”, „Flashback”, „Labirynt” i „Superpozycja”. Podróż w głąb ludzkiej świadomości i podświadomości: o pamięci, granicach wolności, lękach i pragnieniach. Fotografia jako narzędzie dialogu — z samym sobą, z odbiorcą, ze światem. Kuratorka: Agata Rząsowska-Grabicka.",
      en: "Solo exhibition bringing together four of the artist's series — \"Diary of Survival\", \"Flashback\", \"Labyrinth\" and \"Superposition\". A journey into human consciousness and subconsciousness — memory, limits of freedom, fears and desires. Photography as a tool for dialogue — with oneself, the viewer and the world. Curator: Agata Rząsowska-Grabicka."
    },
    images: [
      "images/achievements/w-glowie-sie-nie-miesci-2025/01.webp",
      "images/achievements/w-glowie-sie-nie-miesci-2025/02.webp",
      "images/achievements/w-glowie-sie-nie-miesci-2025/03.webp",
      "images/achievements/w-glowie-sie-nie-miesci-2025/04.webp",
      "images/achievements/w-glowie-sie-nie-miesci-2025/05.webp"
    ]
  },
  {
    id: "rybnik-foto-festival-2025",
    dateISO: "2025-03-28",
    date: {
      pl: "28 marca 2025",
      en: "28 March 2025"
    },
    type: { pl: "Pokaz festiwalowy", en: "Festival screening" },
    title: { pl: "Rybnik Foto Festival — slideshow „Labirynt”", en: "Rybnik Foto Festival — \"Labirynt\" slideshow" },
    place: {
      pl: "Galeria Sztuki Rzeczna, Rybnik",
      en: "Galeria Sztuki Rzeczna, Rybnik"
    },
    description: {
      pl: "Prezentacja slideshow cyklu „Labirynt” na 22. edycji Rybnik Foto Festival. Opowieść o młodych ludziach uwikłanych przez małe miasteczka. Metafora trudności do pokonania i zawiłości życiowych wyborów: czy widz znajdzie drogę wyjścia?",
      en: "Slideshow presentation of the \"Labirynt\" series at the 22nd edition of Rybnik Foto Festival. A story of young people entangled in small towns. A metaphor for difficulties to overcome and the tangled nature of life choices: will the viewer find a way out?"
    },
    links: [
      {
        label: { pl: "Strona festiwalu", en: "Festival website" },
        url: "https://festiwal.rybnik.pl/"
      },
      {
        label: { pl: "Slideshow na YouTube", en: "Slideshow on YouTube" },
        url: "https://www.youtube.com/watch?v=4JCT6mdi9NA"
      },
      {
        label: { pl: "Post festiwalu na Instagramie", en: "Festival's Instagram post" },
        url: "https://www.instagram.com/p/DHIWSF6uK1I/"
      }
    ],
    images: [
      "images/achievements/rybnik-foto-festival-2025/01.webp"
    ]
  },
  {
    id: "10-przykazan-2023",
    dateISO: "2023-09-27",
    date: {
      pl: "27 września – 18 października 2023",
      en: "27 September – 18 October 2023"
    },
    type: { pl: "Wystawa zbiorowa", en: "Group exhibition" },
    title: {
      pl: "10 przykazań",
      en: "10 Commandments"
    },
    place: {
      pl: "Galeria Obok ZPAF, Warszawa",
      en: "Galeria Obok ZPAF, Warsaw"
    },
    address: {
      pl: "Plac Zamkowy 8",
      en: "Plac Zamkowy 8"
    },
    description: {
      pl: "Wystawa zbiorowa będąca owocem rocznej pracy jedenastu słuchaczy Studium Fotografii ZPAF pod kierunkiem Jolanty Rycerskiej. Dekalog — jako temat i wspólny mianownik projektu — skłonił autorów do wizualnych analiz świata wartości, zarówno tych historycznych, wpisanych w naszą kulturę, jak i tych aktualnie przetwarzanych pod wpływem dynamicznych zmian społecznych. Wielogłos pytań, nie odpowiedzi. Kuratorka: Jolanta Rycerska.",
      en: "Group exhibition — the fruit of one year's work by eleven students of the ZPAF School of Photography under the guidance of Jolanta Rycerska. The Decalogue — as theme and common denominator — led the authors to visual analyses of values, both historical, embedded in our culture, and those currently being reworked under dynamic social change. A multi-voice of questions rather than answers. Curator: Jolanta Rycerska."
    },
    links: [
      {
        label: { pl: "Strona wystawy na ZPAF", en: "Exhibition page at ZPAF" },
        url: "https://www.zpaf.pl/aktualnosci/galeria-obok-zpaf/10-przykazan-sluchacze-SF-ZPAF/"
      }
    ],
    images: [
      "images/achievements/10-przykazan-2023/01.webp",
      "images/achievements/10-przykazan-2023/02.webp",
      "images/achievements/10-przykazan-2023/03.webp",
      "images/achievements/10-przykazan-2023/04.webp",
      "images/achievements/10-przykazan-2023/05.webp",
      "images/achievements/10-przykazan-2023/06.webp"
    ]
  }
];

/* ============================================================
   I18N STRINGS
   ============================================================ */
window.I18N = {
  pl: {
    "role": "Artysta wizualny / Fotograf",
    "nav.works": "Prace",
    "nav.achievements": "Aktualności",
    "nav.about": "O autorze",
    "nav.contact": "Kontakt",
    "achievements.h": "Aktualności",
    "home.label": "Prace / Wybrane realizacje",
    "proj.prev": "poprzednie",
    "proj.next": "następne",
    "about.h": "O autorze",
    "contact.h": "Kontakt",
    "lb.close": "Zamknij ✕",
    "cookie.text": "Ta strona używa plików cookies do analizy ruchu (Google Analytics). Pomaga to zrozumieć, jak korzystasz z portfolio. Twoje dane są anonimizowane.",
    "cookie.accept": "Akceptuj",
    "cookie.reject": "Odrzuć",
    "cookie.manage": "Cookies"
  },
  en: {
    "role": "Visual artist / Photographer",
    "nav.works": "Works",
    "nav.achievements": "News",
    "nav.about": "About",
    "nav.contact": "Contact",
    "achievements.h": "News",
    "home.label": "Works / Selected projects",
    "proj.prev": "previous",
    "proj.next": "next",
    "about.h": "About",
    "contact.h": "Contact",
    "lb.close": "Close ✕",
    "cookie.text": "This site uses cookies for traffic analysis (Google Analytics) — to help understand how you interact with the portfolio. Your data is anonymized.",
    "cookie.accept": "Accept",
    "cookie.reject": "Reject",
    "cookie.manage": "Cookies"
  }
};

/* ============================================================
   ABOUT / CONTACT CONTENT
   ============================================================ */
window.ABOUT = {
  pl: {
    body: `<img class="author-portrait" src="images/about/portrait.webp" alt="Paweł Sypniewski — autoportret" loading="lazy" decoding="async">
<p>Paweł Sypniewski (ur. 1987 w Warszawie) — artysta wizualny, fotograf i performer. Członek ZPAF, Okręg Warszawski. W swojej twórczości konsekwentnie wychodzi poza tradycyjnie pojmowane ramy fotografii.</p>
<p>Interesuje go relacja obrazu i tekstu, eksperyment oraz prowokacja, a także łączenie fotografii z innymi środkami wyrazu artystycznego. Jego wszechstronny warsztat sprawia, że trudno sklasyfikować go w obrębie jednego stylu.</p>
<p>W portfolio znajdują się prace dokumentalne, reporterskie, kreacyjne i studyjne, a także realizacje wykorzystujące techniki szlachetne, mixed media i kolaż. Inspiruje się sztuką konceptualną oraz awangardą, tworząc dzieła wymykające się prostym kategoryzacjom.</p>`,
    side: `
<h3>Członkostwo</h3>
<ul>
  <li>ZPAF — Okręg Warszawski</li>
</ul>
<h3>Edukacja</h3>
<ul>
  <li>Instytut Fotografii Twórczej, Opawa</li>
  <li>Program Mentorski Sputnik Photos</li>
  <li>Studium Fotografii ZPAF</li>
</ul>
<h3>Praktyki</h3>
<ul>
  <li>Dokument</li>
  <li>Portret kreacyjny</li>
  <li>Techniki szlachetne</li>
  <li>Mixed media / kolaż</li>
  <li>Performance</li>
</ul>
<h3>Bazy</h3>
<ul>
  <li>Warszawa, PL</li>
  <li>Opawa, CZ</li>
</ul>`
  },
  en: {
    body: `<img class="author-portrait" src="images/about/portrait.webp" alt="Paweł Sypniewski — self-portrait" loading="lazy" decoding="async">
<p>Paweł Sypniewski (born 1987, Warsaw) — visual artist, photographer and performer. Member of ZPAF (Union of Polish Art Photographers), Warsaw Branch. His practice consistently moves beyond the traditional frames of photography.</p>
<p>He is interested in the relation between image and text, experimentation and provocation, and in combining photography with other artistic media. The breadth of his craft makes it difficult to place him within any single style.</p>
<p>His portfolio spans documentary, reportage, constructed and studio work, alongside projects employing historical photographic processes, mixed media and collage. Drawing from conceptual art and the avant-garde, he produces works that resist simple categorisation.</p>`,
    side: `
<h3>Membership</h3>
<ul>
  <li>ZPAF — Warsaw Branch</li>
</ul>
<h3>Education</h3>
<ul>
  <li>Institute of Creative Photography, Opava</li>
  <li>Sputnik Photos Mentor Programme</li>
  <li>ZPAF School of Photography</li>
</ul>
<h3>Practices</h3>
<ul>
  <li>Documentary</li>
  <li>Constructed portrait</li>
  <li>Alternative processes</li>
  <li>Mixed media / collage</li>
  <li>Performance</li>
</ul>
<h3>Based in</h3>
<ul>
  <li>Warsaw, PL</li>
  <li>Opava, CZ</li>
</ul>`
  }
};

/* ============================================================
   INSTAGRAM TILES — 6 zdjęć z folderu /images/instagram/
   Aby zmienić: zastąp pliki 01-06.webp w /images/instagram/.
   Jeśli chcesz linkować konkretne posty, edytuj url poniżej.
   ============================================================ */
const IG_TILES = [
  { img: "images/instagram/01.webp", url: "https://www.instagram.com/p/C5L33N1IeEz/" },
  { img: "images/instagram/02.webp", url: "https://www.instagram.com/p/DDElbqPI8tL/" },
  { img: "images/instagram/03.webp", url: "https://www.instagram.com/p/DCMoYLComsI/" },
  { img: "images/instagram/04.webp", url: "https://www.instagram.com/p/C__MGoGodx7/" },
  { img: "images/instagram/05.webp", url: "https://www.instagram.com/p/DCPeeERoB0_/" },
  { img: "images/instagram/06.webp", url: "https://www.instagram.com/p/DGbNquTI_p8/" }
];

function buildIgSection(L) {
  const heading = L === "pl" ? "Codziennie na Instagramie" : "Daily on Instagram";
  const aria    = L === "pl" ? "Zobacz post na Instagramie" : "View on Instagram";
  const tiles = IG_TILES.map(t =>
    `<a class="ig-tile" href="${t.url}" target="_blank" rel="noopener noreferrer" aria-label="${aria}" style="background-image:url('${t.img}')"></a>`
  ).join("");
  return `
<div class="ig-section">
  <div class="ig-heading">${heading}</div>
  <div class="ig-grid">${tiles}</div>
  <a class="ig-more" href="https://www.instagram.com/sypniewskistudio/" target="_blank" rel="noopener noreferrer">@sypniewskistudio →</a>
</div>`;
}

window.CONTACT = {
  pl: {
    body: `<p>Odbitki autorskie w limitowanych edycjach są dostępne w sprzedaży. Możesz zapytać o dowolne zdjęcie, które Cię zainteresowało. W sprawie nakładu, formatów i cen — napisz do mnie mailem.</p>` + buildIgSection("pl"),
    side: `
<h3>E-mail</h3>
<ul><li><a href="mailto:katedranalogowa@gmail.com">katedranalogowa@gmail.com</a></li></ul>
<h3>Instagram</h3>
<ul><li><a href="https://www.instagram.com/sypniewskistudio/" target="_blank" rel="noopener">@sypniewskistudio</a></li></ul>`
  },
  en: {
    body: `<p>Limited edition prints are available for sale. Please ask for any picture you like. For details — amounts, sizes, pricing — send me an email.</p>` + buildIgSection("en"),
    side: `
<h3>E-mail</h3>
<ul><li><a href="mailto:katedranalogowa@gmail.com">katedranalogowa@gmail.com</a></li></ul>
<h3>Instagram</h3>
<ul><li><a href="https://www.instagram.com/sypniewskistudio/" target="_blank" rel="noopener">@sypniewskistudio</a></li></ul>`
  }
};
